services:
  node:
    image: node:22
    container_name: fine_tracker
    working_dir: /app
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./node_modules:/app/node_modules
      - ./.env:/app/.env
      - ./package-lock.json:/app/package-lock.json
      - ./tsconfig.build.json:/app/tsconfig.build.json
      - ./tsconfig.json:/app/tsconfig.json
    ports:
      - '3000:3000'
    command: ['npm', 'run', 'start']
    networks:
      - fine_tracker
    restart: 'no'
  postgres:
    container_name: fine_tracker_db
    image: postgres:latest
    environment:
      POSTGRES_DB: fine_tracker
      POSTGRES_USER: tracker
      POSTGRES_PASSWORD: tracker_2025
    volumes:
      - fine_tracker_db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - fine_tracker
    restart: 'no'
volumes:
  fine_tracker_db:
    driver: local
networks:
  fine_tracker:
    driver: bridge
